name: bavartec_stc

dependencies:
  flutter:
    sdk: flutter

  connectivity: ^0.4.4
  http: ^0.12.0
  multicast_dns: ^0.2.0
  mqtt_client: ^5.5.4
  shared_preferences: ^0.5.3
  smartconfig: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#00ABFA"
  adaptive_icon_foreground: "assets/icon_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/manual/
    - assets/manual/dip/
