name: bavartec_stc

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^3.2.2
  connectivity: ^0.4.4
  http: ^0.12.0
  multicast_dns: ^0.2.0
  mqtt_client: ^5.5.4
  shared_preferences: ^0.5.3
  smartconfig: ^0.0.1
  #fluttertoast: ^2.1.1
  #flutter_mdns_plugin: ^0.0.1
  #mdns2: ^0.0.1
  #flutter_mdns_plugin:
  #  git: https://github.com/terrabythia/flutter_mdns_plugin.git

  #多语言插件
  flutter_localizations:
    sdk: flutter
  intl: 0.15.8
  intl_translation: 0.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#00ABFA"
  adaptive_icon_foreground: "assets/icon_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/manual/
    - assets/manual/dip/
