name: bavartec_stc

dependencies:
  flutter:
    sdk: flutter
  #多语言插件
  flutter_localizations:
    sdk: flutter

  connectivity: ^0.4.5
  device_info: ^0.4.1
  http: ^0.12.0
  intl: ">=0.15.8"
  intl_translation: ^0.17.7
  mqtt_client: ^5.6.2
  url_launcher: ^5.2.7
  shared_preferences: ^0.5.4
  smartconfig: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#00ABFA"
  adaptive_icon_foreground: "assets/icon_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/manual/
    - assets/manual/dip/
